sudo: required
services:
  - docker

env:
  global:
    # specify variable for unique image tagging
    - SHA=$(git rev-parse HEAD)
    # prevent gcloud from interactive prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # install google cloud sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  ## configure it
  - source $HOME/google-cloud-sdk/path.bash.inc
  ## install kubectl
  - gcloud components update kubectl

  # configure the sdk without google cloud auth info
  ## decrypt the servce-account.json on Travis
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  ## authenticate against GCP with the generated service-account.json
  - gcloud auth activate-service-account --key-file service-account.json
  ## target project
  - gcloud config set project k8s-learning-297809
  ## specify compute zone
  - gcloud config set compute/zone us-central1-c
  ## specify target cluster
  - gcloud container clusters get-credentials multi-cluster

  # login to dock cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

  # build the test version of multi-client
  - docker build -t jackula83/react-test -f client/Dockerfile.dev ./client

# run tests
script:
  - docker run -e CI=true jackula83/react-test npm test

# if tests are successful, run a script to deploy newest images
deploy:
  provider: script
  script: bash ./deploy.sh
  # only run on main
  on:
    branch: main
