version: 2.1
description: DigitalOcean Kubernetes Engine Orb
orbs:
  doctl: digitalocean/cli@0.1.1
  k8s: circleci/kubernetes@0.1.0
  # jobs:
  #   build:
  #     machine: true
  #     steps:
  #       - checkout
  #       # build and push Docker image
  #       - run:
  #           name: BuildPushDockerImages
  #           command: |
  #             echo $CIRCLE_BUILD_NUM
  #             docker build -t jackula83/multi-client:latest -t jackula83/multi-client:$CIRCLE_BUILD_NUM ./client
  #             docker build -t jackula83/multi-server:latest -t jackula83/multi-server:$CIRCLE_BUILD_NUM ./server
  #             docker build -t jackula83/multi-worker:latest -t jackula83/multi-worker:$CIRCLE_BUILD_NUM ./worker
  #             echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin docker.io
  #             docker push jackula83/multi-client:latest
  #             docker push jackula83/multi-server:latest
  #             docker push jackula83/multi-worker:latest
  #             docker push jackula83/multi-client:$CIRCLE_BUILD_NUM
  #             docker push jackula83/multi-server:$CIRCLE_BUILD_NUM
  #             docker push jackula83/multi-worker:$CIRCLE_BUILD_NUM
  deploy:
    description: Deploy application to DigitalOcean Kubernetes
    machine: true
    steps:
      - checkout
      # Install `doctl` and `kubectl` if not already installed.
      - doctl/install
      - k8s/install
      # Initialise doctl
      - initialize:
          parameters:
          cluster:
            description: 'geekmotors-main-cluster'
            type: string
      # Configure and apply all k8s config files
      - run:
          name: ApplyK8sConfig
          command: |
            doctl kubernetes cluster kubeconfig save geekmotors-main-cluster
            kubectl apply -f k8s
      - run: echo $CIRCLE_BUILD_NUM
      # Update a deployment Docker images.
      - run:
          name: UpdateDeployments
          command: |
            doctl kubernetes cluster kubeconfig save geekmotors-main-cluster
            kubectl set image deployment/server-deployment server=jackula83/multi-server:latest
            kubectl set image deployment/client-deployment client=jackula83/multi-client:latest
            kubectl set image deployment/worker-deployment worker=jackula83/multi-worker:latest
workflows:
  build_update_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
